# PBS script

module load python/2.7.7
cd /nv/hcoc1/rchen87/tensor_factorization/github_tensor/htn_expt_run/
echo "started on `/bin/hostname`"

mpirun -np 8 python ../experiment_code/loadtensor_runfactorization_printphenotypes.py 50 1 0.001,0.04,0.04 /nv/pcoc1/rchen87/tensor_factorization/github_tensor/htn_data_tensors/htn-tensor-subsetforanalysis-20140811-{0}.dat /nv/pcoc1/rchen87/tensor_factorization/github_tensor/experiment_code/ /nv/pcoc1/rchen87/tensor_factorization/github_tensor/htn_expt_run/output_20140828/
