# PBS script
#PBS -N marble_diff_gammas
#PBS -l nodes=1:ppn=8:nvidiagpu
#PBS -l mem=8gb
#PBS -l walltime=15:00:00
#PBS -q monkeys
#PBS -j oe
#PBS -o marble_gamma_0.001-0.02-0.02.out
#PBS -m abe
#PBS -M rchen87@gatech.edu

cd /nv/hcoc1/rchen87/tensor_factorization/github_tensor/htn_expt_run/
echo "started on `/bin/hostname`"

mpirun -np 8 python ../experiment_code/loadtensor_runfactorization_printphenotypes.py 50 1 0.001,0.02,0.02 /nv/pcoc1/rchen87/tensor_factorization/github_tensor/htn_data_tensors/htn-tensor-subsetforanalysis-20140811-{0}.dat /nv/pcoc1/rchen87/tensor_factorization/github_tensor/experiment_code/ /nv/pcoc1/rchen87/tensor_factorization/github_tensor/htn_expt_run/output_20140828/
